from django.urls import path

from .api import (
    CustomerBillRequestView,
    CustomerBillView,
    CustomerMenuView,
    CustomerOrderDetailView,
    CustomerOrderListCreateView,
    CustomerPaymentDemoView,
    CustomerSessionCreateView,
    CustomerTableView,
    StaffBillPaidView,
    StaffBillSendView,
    StaffBillsView,
    StaffCategoriesView,
    StaffCategoryDetailView,
    StaffDashboardView,
    StaffLoginView,
    StaffMenuAvailabilityView,
    StaffMenuDetailView,
    StaffMenuSpecialView,
    StaffMenuView,
    StaffOrderStatusView,
    StaffOrdersView,
    StaffTableCloseView,
    StaffTableOpenView,
    StaffTablesView,
    CustomerTableAssistantView,
    StaffTableAssistantView,
    StaffOrderItemRejectView,
)


urlpatterns = [
    path("customer/table/<slug:restaurant_slug>/<uuid:table_id>/", CustomerTableView.as_view()),
    path("customer/sessions/", CustomerSessionCreateView.as_view()),
    path("customer/menu/", CustomerMenuView.as_view()),
    path("customer/orders/", CustomerOrderListCreateView.as_view()),
    path("customer/orders/<uuid:order_id>/", CustomerOrderDetailView.as_view()),
    path("customer/bill/", CustomerBillView.as_view()),
    path("customer/bill/request/", CustomerBillRequestView.as_view()),
    path("customer/payment/demo/", CustomerPaymentDemoView.as_view()),
    path("staff/login/", StaffLoginView.as_view()),
    path("staff/dashboard/", StaffDashboardView.as_view()),
    path("staff/tables/", StaffTablesView.as_view()),
    path("staff/tables/<uuid:table_id>/open/", StaffTableOpenView.as_view()),
    path("staff/tables/<uuid:table_id>/close/", StaffTableCloseView.as_view()),
    path("staff/orders/", StaffOrdersView.as_view()),
    path("staff/orders/<uuid:order_id>/status/", StaffOrderStatusView.as_view()),
    path("staff/categories/", StaffCategoriesView.as_view()),
    path("staff/categories/<uuid:category_id>/", StaffCategoryDetailView.as_view()),
    path("staff/menu/", StaffMenuView.as_view()),
    path("staff/menu/<uuid:item_id>/", StaffMenuDetailView.as_view()),
    path("staff/menu/<uuid:item_id>/availability/", StaffMenuAvailabilityView.as_view()),
    path("staff/menu/<uuid:item_id>/special/", StaffMenuSpecialView.as_view()),
    path("staff/bills/", StaffBillsView.as_view()),
    path("staff/bills/<uuid:bill_id>/paid/", StaffBillPaidView.as_view()),
    path("staff/bills/<uuid:bill_id>/send/", StaffBillSendView.as_view()),
    path("customer/assistant/", CustomerTableAssistantView.as_view()),
    path("staff/assistant/", StaffTableAssistantView.as_view()),
    path("staff/assistant/<uuid:request_id>/", StaffTableAssistantView.as_view()),
    
    path("staff/orders/items/<uuid:item_id>/reject/", StaffOrderItemRejectView.as_view()),
]
