# Generated by Django 6.1 on 2026-08-20 17:55

import sessions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersession',
            name='expires_at',
            field=models.DateTimeField(default=sessions.models.default_expiry),
        ),
    ]
