# Generated by Django 6.1 on 2026-08-22 09:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_bill_and_order_details'),
        ('restaurants', '0002_restaurant_details'),
        ('tables', '0003_alter_diningsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='additional_charges',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.13'), max_digits=4),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='rejection_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('WATER', 'Request Water'), ('PLATE', 'Extra Plate'), ('CUTLERY', 'Cutlery'), ('NAPKINS', 'Napkins'), ('CHAIR', 'Extra Chair'), ('STAFF', 'Call Staff'), ('BILL', 'Request Bill'), ('CUSTOM', 'Custom Request')], default='WATER', max_length=20)),
                ('custom_note', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACKNOWLEDGED', 'Acknowledged'), ('FULFILLED', 'Fulfilled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dining_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='tables.diningsession')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
